### PR TITLE
Less harmonious "module" keyword

### PR DESCRIPTION
**Pull request by GregorR**
I'm using Narcissus to parse out-there-in-the-horrible-wild-web JavaScript code. Unfortunately, the addition of "module" as a keyword (for Harmony) has broken my parsing of some things from Google, as they use "module" as an identifier. Although the module /statement/ is blacklisted in the parser, it's still interpreted as a keyword in the lexer, so it just fails to parse.

I've added a similar blacklist to the lexer module, which causes the listed keywords to be treated as identifiers. The only keyword listed is MODULE of course (since the other two which are blacklisted statements, import and export, are future-use keywords by the ECMAScript spec), but that was sufficient for me to parse more Googcode.

Having this in a separate blacklist in a separate module is probably far from ideal. If you have another suggestion for how to organize it, I'll change it and send another pull request.

### CODE REVIEW

**Comment by GregorR** [comment]
Upon further investigation, my changes are partially ambiguous with bjouhier's pull request regarding keywords as identifiers. However, I think both are necessary.

**Comment by taustin** [comment]
It looks good, though there were two new failures.  Can you review them and make sure there is no major problem there?

Test results below:

[1511|   2| 155] 100% ===============================================>|  883.4s
FIXES
    js1_7/decompilation/regress-349634.js
    js1_7/extensions/regress-353214-02.js
TIMEOUTS
    js1_5/extensions/regress-371636.js
    js1_5/GC/regress-278725.js
FAIL

**Comment by taustin** [comment]
It looks like these changes have been collapsed into https://github.com/mozilla/narcissus/pull/30.  Can we close this ticket?

**Comment by GregorR** [comment]
Yes, this can be closed. I'll handle #30 too.

**Pull request closed without merging**
