### PR TITLE
Removing jsbrowser.js and adding (limited) support for lets in interpreter

### PR DESCRIPTION
**Pull request by taustin**
This PR removes jsbrowser.js, since it does not seem to be used outside of Zaphod.  I'm moving that file over to Zaphod instead.

Also, adding support to treat let as a synonym for var in the interpreter until a more permanent solution can be created.

### CODE REVIEW

**Comment by syg** [comment]
Removing `jsbrowser.js` is fine with me, but I'd rather that we not treat `let`s as `var`s, which could introduce subtle scope-related.

**Comment by taustin** [comment]
I've disabled treating lets as vars by default.  Now it will throw a 'let not yet implemented' error instead.

**Comment by taustin** [comment]
Removed let as vars functionality.  Includes support for destructuring assignment.

**Comment by dherman** [comment]
The lets-as-vars stuff is fine with me as a stop-gap, and removing jsbrowser.js is great. But the destructuring isn't so great.

**Comment by taustin** [comment]
After talking with Dave, we're going to restrict jsexec to ES3.  I'm closing this request and will reopen a new one with just the relevant features.

**Pull request closed without merging**
