### PR TITLE
package.json for npm + minor bugfix

### PR DESCRIPTION
**Pull request by bjouhier**
I am using narcissus in one of my node.js projects (https://github.com/Sage/streamlinejs) and I would like to be able to install my package with NPM (node package manager). For this I need an NPM installer for narcissus.

So I created a package.json file for narcissus. I have set the version number to 0.1.0 because I could not find one. It should probably be changed. I did not set any "engine" dependency because narcisssus does not have direct dependencies on node.

To complete the process, narcissus need to be "published" to NPM. I could do it but I would probably need to be authorized by Mozilla to do so. So it is probably better if it gets published directly by Mozilla. The steps are simple and described on https://github.com/isaacs/npm/blob/master/doc/developers.md#readme 

I also fixed a really minor bug in the decompiler. It was generating invalid code for empty property names in object initializer: var foo = { "": "hello" }; --> var foo = { : "hello" }; The fix was trivial.

Note: I just completed the process to obtain the committer's agreement. My request has not been approved yet but the bug report is here: https://bugzilla.mozilla.org/show_bug.cgi?id=631785

And BTW, kudos to all involved for creating this great component. 

Bruno

### CODE REVIEW

**Comment by dherman** [comment]
Hey Bruno, this is awesome! Thanks so much for the patch and the great ideas. I will take care of all of this early next week. Thanks especially for filling out the committer's agreement -- that should help speed things along.

Best,
Dave Herman

**Comment by bjouhier** [comment]
Thanks Dave.

**Comment by bjouhier** [comment]
Hi Dave, 

Version number should be 0.0.1 now. 

Bruno

**Comment by codeflows** [comment]
Hi,

I tried installing Narcissus via NPM using Bruno's fork and it works. In order to use the parser, I had to require three files,
which wasn't obvious straight away:

```
require('narcissus/jsdefs')
require('narcissus/jslex')
require('narcissus/jsparse')
```

This puts the Narcissus stuff in the global namespace, so I can then do

```
Narcissus.parser.parse('var x = 1')
```

Intuitively (based on other node/NPM modules I've used) I expected to be able to do

```
var parser = require('narcissus').parser
parser.parse('var x = 1')
```

that is, load the module more according to the CommonJS module spec: http://www.commonjs.org/specs/modules/1.0/

In order for this to work, you need to have a "main" module definition in package.json. A quick'n'dirty example in my fork: https://github.com/codeflows/narcissus/commit/71df5ec8c80a952d944a829f30f2ff2e23849029

Perhaps a better idea would be to have a thin CommonJS module "compatibility" layer for all the modules in Narcissus, so that I could do any of

```
var lexer = require('narcissus').lexer // require loads and exposes all the modules,
                                       // we just use the lexer
var lexer = require('narcissus/lexer') // require only loads lexer-module + its deps
```

Food for thought :) Nice library btw!
- Jari

**Comment by dherman** [comment]
Hi Jari,

We've talked about CommonJS compatibility in the past but we didn't really see it through. I think your idea is pretty reasonable. It's kind of cheating because we shouldn't be using a global Narcissus variable, but it's better than nothing, at least for now. Maybe in the future we can come up with a cleaner solution.

I'll go ahead and implement these wrappers. Thanks for the suggestion!

Thanks,
Dave

**Comment by dherman** [comment]
Pushed and published to NPM! Thanks for your help, guys.

Dave

**Pull request merged**
