### PR TITLE
Support for unicode identifiers

### PR DESCRIPTION
**Pull request by GregorR**
I've added support for identifiers with Unicode characters. Right now I test this with the following crazy metacircular function:

```
function isValidIdentifierChar(ch, first) {
    // create an object to test this in
    var x = {};
    x["x"+ch] = true;
    x[ch] = true;

    // then try
    try {
        return (eval("(x." + (first?"":"x") + ch + ")") ? true : false);
    } catch (ex) {
        return false;
    }
}
```

This is enormously unsafe if ch is more than one codepoint, but harmless if it isn't. I had to do it this way because JavaScript doesn't provide (as far as I could tell?) a way of determining the Unicode category of a given codepoint, so I just have to trust the host parser to know that.

This function is only called for high-Unicode (>ASCII) codepoints.

### CODE REVIEW

**Comment by GregorR** [comment]
Note that I did it this way after spending ten minutes compiling a database of all the relevant Unicode codepoints. I vote we don't do that :P

**Comment by GregorR** [comment]
I moved things around a bit, I think it's clearer now, plus it supports \u.... identifiers.

**Comment by taustin** [comment]
I attempted to merge in these changes with the latest version, but I ended up getting some new unit test failures.  (My merging may be to blame).

Can you investigate?  Here are a handful of the failing tests:

```
ecma/Array/15.4-1.js
ecma/Array/15.4-2.js
ecma/Array/15.4.1.js
ecma/Array/15.4.3.1-2.js
ecma/Array/15.4.4.4-1.js
ecma/Array/15.4.4.4-2.js
ecma/Array/15.4.4.5-1.js
ecma/Array/15.4.4.5-2.js
```

**Comment by taustin** [comment]
Looks good.  r=me

**Pull request merged**
